name: SonarCloud Analysis

on:
  workflow_run:
    workflows: ["Odoo CI/CD Pipeline"]
    types: [completed]
  workflow_dispatch:

jobs:
  sonarqube:
    name: "SonarCloud Scan"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage report
        if: github.event_name == 'workflow_run'
        uses: actions/download-artifact@v4
        with:
          name: odoo-test-logs
          path: .
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@094fb4bef2a106e232598f48035ed88661642230
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
